from typing import List

class Solution:
    def findAnagrams(self, s: str, p: str) -> List[int]:
        res = []
        
        if len(p) > len(s):
            return res
        
        def compareCounters(c1, c2) -> bool:
            for c in c1:
                if c not in c2 or c1[c] != c2[c]:
                    return False
            return True
        
        fCounterP = {}
        fCounterS = {}

        for i in range(0,len(p)):
            if p[i] not in fCounterP:
                fCounterP[p[i]] = 0
            fCounterP[p[i]] += 1
            
            if s[i] not in fCounterS:
                fCounterS[s[i]] = 0
            fCounterS[s[i]] += 1

        if (compareCounters(fCounterP, fCounterS)):
            res.append(0);

        i = 1
        j = i+len(p)-1
        
        while j < len(s):
            if s[j] not in fCounterS:
                fCounterS[s[j]] = 0
            fCounterS[s[j]] += 1
            fCounterS[s[i-1]] -= 1
            
#            print("S:", fCounterS)
            
            if (compareCounters(fCounterP, fCounterS)):
                res.append(i);
            
            i+=1
            j+=1

        return res

        
s = Solution()        
res = s.findAnagrams("cbaebabacd", "abc")
print(res)

res = s.findAnagrams("abab", "ab")
print(res)

res = s.findAnagrams("", "a")
print(res)

res = s.findAnagrams("aa", "bb")
print(res)

res = s.findAnagrams("lzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajw", "l")
print(res)

