from typing import List

class Solution:
    def checkInclusion(self, s1: str, s2: str) -> bool:
        if len(s1) > len(s2) or (s1 == "" and s2 != ""):
            return False
        
        def compareCounters(c1, c2) -> bool:
            for c in c1:
                if c not in c2 or c1[c] != c2[c]:
                    return False
            return True
        
        fCounter1 = {}
        fCounter2 = {}

        for i in range(0,len(s1)):
            if s1[i] not in fCounter1:
                fCounter1[s1[i]] = 0
            fCounter1[s1[i]] += 1
            
            if s2[i] not in fCounter2:
                fCounter2[s2[i]] = 0
            fCounter2[s2[i]] += 1

        if (compareCounters(fCounter1, fCounter2)):
            return True

        i = 1
        j = i+len(s1)-1
        
        while j < len(s2):
            if s2[j] not in fCounter2:
                fCounter2[s2[j]] = 0
            fCounter2[s2[j]] += 1
            fCounter2[s2[i-1]] -= 1
            
            if (compareCounters(fCounter1, fCounter2)):
                return True
            
            i+=1
            j+=1

        return False

        
s = Solution()        
res = s.checkInclusion("ab", "eidbaooo")
print(res)

res = s.checkInclusion("ab", "eidboaoo")
print(res)

res = s.checkInclusion("", "a")
print(res)

res = s.checkInclusion("aa", "bb")
print(res)

res = s.checkInclusion("ab", "lzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajwlzfkvcrutnehgdopmixyqsbajw")
print(res)

